app-deployment:
  appName: video-manager-client
  deployment:
    image: nexus-docker-craigmiller160.ddns.net/video-manager-client:latest
    ports:
      - 443
    livenessProbe:
      httpGet:
        path: /healthcheck
        port: 443
        scheme: HTTPS
  service:
    enable: true
    type: ClusterIP
    ports:
      - containerPort: 443