app_deployment:
  appName: market-tracker-ui
  image: nexus-docker-craigmiller160.ddns.net/market-tracker-ui:latest
  ports:
    - containerPort: 443
  commonProbe:
    httpGet:
      path: /healthcheck
      port: 443
      scheme: HTTPS
  secure_ingress:
    name: market-tracker-ingress
    backendIsHttps: true
    hosts:
      - name: apps.craigmiller160.us
        services:
          - path: /(market-tracker(/.*)?)
            serviceName: market-tracker-ui
            portNumber: 443