app-deployment:
  appName: market-tracker-ui
  image: nexus-docker-craigmiller160.ddns.net/market-tracker-ui:latest
  ports:
    - containerPort: 443
  livenessProbe:
    httpGet:
      path: /healthcheck
      port: 443
      scheme: HTTPS