apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-tracker-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-tracker-ui
  template:
    metadata:
      labels:
        app: market-tracker-ui
    spec:
      containers:
        - name: market-tracker-ui
          image: craigmiller160.ddns.net:30004/market-tracker-ui:${KUBE_IMG_VERSION}
          ports:
            - containerPort: 443
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 443
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 300
---
apiVersion: v1
kind: Service
metadata:
  name: market-tracker-ui-service
spec:
  type: ClusterIP
  selector:
    app: market-tracker-ui
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
